package com.boutique.order.service;
import com.boutique.order.dto.*;import com.boutique.order.entity.*;import com.boutique.order.repository.*;import tools.jackson.databind.ObjectMapper;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class OrderService { private final OrderRepository orders;private final OutboxRepository outbox;private final ObjectMapper json; public OrderService(OrderRepository o,OutboxRepository x,ObjectMapper j){orders=o;outbox=x;json=j;}
 @Transactional public OrderResponse create(CreateOrderRequest r){return orders.findByIdempotencyKey(r.idempotencyKey()).map(OrderResponse::from).orElseGet(()->{OrderEntity o=new OrderEntity(r.userId(),r.idempotencyKey(),r.total(),r.currency().toUpperCase());r.items().forEach(i->o.addItem(new OrderItemEntity(i.productId(),i.sku(),i.name(),i.unitPrice(),i.quantity(),i.lineTotal())));orders.save(o);event(o,"ORDER_CREATED");return OrderResponse.from(o);});}
 @Transactional(readOnly=true) public OrderResponse get(UUID id){return OrderResponse.from(find(id));}
 @Transactional public OrderResponse confirm(UUID id,UUID paymentId){OrderEntity o=find(id);if(o.getStatus()==OrderStatus.CONFIRMED)return OrderResponse.from(o);if(o.getStatus()!=OrderStatus.PENDING)throw new IllegalStateException("Only PENDING orders can be confirmed");o.confirm(paymentId);event(o,"ORDER_CONFIRMED");return OrderResponse.from(o);}
 @Transactional public void paymentFailed(UUID id){OrderEntity o=find(id);if(o.getStatus()==OrderStatus.PENDING){o.paymentFailed();event(o,"ORDER_PAYMENT_FAILED");}}
 private OrderEntity find(UUID id){return orders.findById(id).orElseThrow(()->new NoSuchElementException("Order not found: "+id));}
 private void event(OrderEntity o,String type){try{Map<String,Object> p=new LinkedHashMap<>();p.put("eventId",UUID.randomUUID());p.put("eventType",type);p.put("orderId",o.getId());p.put("userId",o.getUserId());p.put("paymentId",o.getPaymentId());p.put("status",o.getStatus().name());p.put("total",o.getTotal());p.put("currency",o.getCurrency());p.put("occurredAt",java.time.Instant.now());outbox.save(new OutboxEvent(o.getId(),type,json.writeValueAsString(p)));}catch(Exception e){throw new IllegalStateException("Cannot serialize order event",e);}}
}
