server:
  port: ${SERVER_PORT:8084}
  shutdown: graceful
  tomcat:
    threads:
      max: ${SERVER_TOMCAT_MAX_THREADS:64}
      min-spare: ${SERVER_TOMCAT_MIN_SPARE_THREADS:10}
    accept-count: ${SERVER_TOMCAT_ACCEPT_COUNT:200}
    max-connections: ${SERVER_TOMCAT_MAX_CONNECTIONS:2000}
spring:
  application:
    name: boutique-orderservice
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${DB_USERNAME:boutique_admin}
    password: ${DB_PASSWORD:boutique_local_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      acks: all
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
app:
  kafka:
    order-events-topic: ${KAFKA_ORDER_EVENTS_TOPIC:boutique.order.events}
  outbox:
    publish-delay-ms: ${OUTBOX_PUBLISH_DELAY_MS:1000}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
